# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VthCli < Formula
  desc ""
  homepage "https://azarc.io/"
  version "1.0.0"
  license "Apache"
  depends_on :linux

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/azarc-io/vth-cli/releases/download/v1.0.0/vth-cli-1.0.0-Linux-arm64.tar.gz"
      sha256 "a2d5c5586e35ae58e60994597725fd44e3256640ed302ae4fa2c79fd376f2f3a"

      def install
        bin.install "vth-cli-1.0.0-linux-arm64"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/azarc-io/vth-cli/releases/download/v1.0.0/vth-cli-1.0.0-Linux-x86_64.tar.gz"
      sha256 "2e7d23f41c8b4bab32c02b1e5437ddaa8395001a0b431d95f7d7dd056608648b"

      def install
        bin.install "vth-cli-1.0.0-linux-amd64"
      end
    end
  end
end
