# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VthCli < Formula
  desc "Verathread CLI"
  homepage "https://azarc.io/"
  version "1.0.0"
  license "Apache"

  on_macos do
    if Hardware::CPU.arm?
      url "https://vth-artifacts.s3.eu-west-1.amazonaws.com/cli_v2/v1.0.0/vth-cli-1.0.0-Darwin-arm64.tar.gz"
      sha256 "9a09c1996c7e98cbcf17433b28b59d042803073a37b6d051b7a697b629d30bd6"

      def install
        bin.install "vth2"
      end
    end
    if Hardware::CPU.intel?
      url "https://vth-artifacts.s3.eu-west-1.amazonaws.com/cli_v2/v1.0.0/vth-cli-1.0.0-Darwin-x86_64.tar.gz"
      sha256 "64d8078880009a0486a6dd6730eb1cd80955339f58165d538144227aea946847"

      def install
        bin.install "vth2"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://vth-artifacts.s3.eu-west-1.amazonaws.com/cli_v2/v1.0.0/vth-cli-1.0.0-Linux-arm64.tar.gz"
      sha256 "d80114cd45305f2b46f79131ddf998237c057daeba3714bad560634b74980426"

      def install
        bin.install "vth2"
      end
    end
    if Hardware::CPU.intel?
      url "https://vth-artifacts.s3.eu-west-1.amazonaws.com/cli_v2/v1.0.0/vth-cli-1.0.0-Linux-x86_64.tar.gz"
      sha256 "a4497f55f60366ab47d8e8b0a7dbf6fcdb5a265b3d4e4db945ac1a29ed2ebd5c"

      def install
        bin.install "vth2"
      end
    end
  end

  test do
    system "#{bin}/vth2 version"
  end
end
