# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class VthCli < Formula
  desc "Verathread CLI"
  homepage "https://azarc.io/"
  version "1.0.0"
  license "Apache"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/azarc-io/vth-cli/releases/download/v1.0.0/vth-cli-1.0.0-Darwin-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "9bbf47b85aa4ab5d0a640ab262d84fd31c92343fc5e3ab48947f6b2b2b0c4621"

      def install
        bin.install "vth2"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/azarc-io/vth-cli/releases/download/v1.0.0/vth-cli-1.0.0-Darwin-x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "67bc9189fe6c1e165228b6e8ce817a58c21e47f051977af92c8456d8c0382adb"

      def install
        bin.install "vth2"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/azarc-io/vth-cli/releases/download/v1.0.0/vth-cli-1.0.0-Linux-arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "dfce2dcc7e053955f418e742bb4c196db1f17cf8325e6412072f7762820ed4e7"

      def install
        bin.install "vth2"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/azarc-io/vth-cli/releases/download/v1.0.0/vth-cli-1.0.0-Linux-x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "7f97dfb1d000081c1b09b22dc397f19fd632274694bae8ff1caa380852972e56"

      def install
        bin.install "vth2"
      end
    end
  end

  test do
    system "#{bin}/vth2 -v"
  end
end
