# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VthCli < Formula
  desc "Verathread CLI"
  homepage "https://azarc.io/"
  version "1.19.0"
  license "Apache"

  on_macos do
    if Hardware::CPU.intel?
      url "https://vth-artifacts.s3.eu-west-1.amazonaws.com/cli_v2/v1.19.0/vth-cli-1.19.0-Darwin-x86_64.tar.gz"
      sha256 "306fbf060fc88b2149754db4971c423d610ad737407456cd8f1963d39bbb1dc1"

      def install
        bin.install "vth2"
      end
    end
    if Hardware::CPU.arm?
      url "https://vth-artifacts.s3.eu-west-1.amazonaws.com/cli_v2/v1.19.0/vth-cli-1.19.0-Darwin-arm64.tar.gz"
      sha256 "c28161d55a493fe8e4e6ba3b05f4a9c80548c1e86abb12585a06bf571f1032bf"

      def install
        bin.install "vth2"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://vth-artifacts.s3.eu-west-1.amazonaws.com/cli_v2/v1.19.0/vth-cli-1.19.0-Linux-arm64.tar.gz"
      sha256 "19225e61ca607d8ab3960f12a00c757a0f74ad52632bd960ba5941f41deeb170"

      def install
        bin.install "vth2"
      end
    end
    if Hardware::CPU.intel?
      url "https://vth-artifacts.s3.eu-west-1.amazonaws.com/cli_v2/v1.19.0/vth-cli-1.19.0-Linux-x86_64.tar.gz"
      sha256 "0666595d48388ef14a9d0c02cf11e5d40d490170fab9cbbaa8c428f46d4c0be9"

      def install
        bin.install "vth2"
      end
    end
  end

  test do
    system "#{bin}/vth2 version"
  end
end
